all:
	g++ ../cards/card.h ../cards/card.cpp ../dice/dice.h ../dice/dice.cpp ../dice/die.h ../dice/die.cpp player.h player.cpp main.cpp -o main

.PHONY: all

clean:
	rm -rf player.h.gch main

.PHONY: clean
